/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.sorting.services.SortingGrammarAccess;
import org.xtext.example.sorting.sorting.Config;
import org.xtext.example.sorting.sorting.Filter;
import org.xtext.example.sorting.sorting.Instance;
import org.xtext.example.sorting.sorting.Sink;
import org.xtext.example.sorting.sorting.SortingPackage;
import org.xtext.example.sorting.sorting.Source;
import org.xtext.example.sorting.sorting.Transition;
import org.xtext.example.sorting.sorting.Type;

@SuppressWarnings("all")
public class SortingSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SortingGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SortingPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SortingPackage.CONFIG:
				sequence_Config(context, (Config) semanticObject); 
				return; 
			case SortingPackage.FILTER:
				sequence_Filter(context, (Filter) semanticObject); 
				return; 
			case SortingPackage.INSTANCE:
				sequence_Instance(context, (Instance) semanticObject); 
				return; 
			case SortingPackage.SINK:
				sequence_Sink(context, (Sink) semanticObject); 
				return; 
			case SortingPackage.SOURCE:
				sequence_Source(context, (Source) semanticObject); 
				return; 
			case SortingPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			case SortingPackage.TYPE:
				sequence_Type(context, (Type) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Config returns Config
	 *
	 * Constraint:
	 *     (name=ID components+=Component transitions+=Transition)
	 */
	protected void sequence_Config(ISerializationContext context, Config semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Component returns Filter
	 *     Filter returns Filter
	 *
	 * Constraint:
	 *     (name=ID inType=Type outType=Type method=STRING?)
	 */
	protected void sequence_Filter(ISerializationContext context, Filter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Component returns Instance
	 *     Instance returns Instance
	 *
	 * Constraint:
	 *     (component=[Component|ID] name=ID (method=STRING | args+=STRING+)?)
	 */
	protected void sequence_Instance(ISerializationContext context, Instance semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Component returns Sink
	 *     Sink returns Sink
	 *
	 * Constraint:
	 *     (name=ID inType=Type method=STRING?)
	 */
	protected void sequence_Sink(ISerializationContext context, Sink semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Component returns Source
	 *     Source returns Source
	 *
	 * Constraint:
	 *     (name=ID type=Type method=STRING?)
	 */
	protected void sequence_Source(ISerializationContext context, Source semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (source=[Component|ID] target=[Component|ID])
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SortingPackage.Literals.TRANSITION__SOURCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SortingPackage.Literals.TRANSITION__SOURCE));
			if (transientValues.isValueTransient(semanticObject, SortingPackage.Literals.TRANSITION__TARGET) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SortingPackage.Literals.TRANSITION__TARGET));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTransitionAccess().getSourceComponentIDTerminalRuleCall_0_0_1(), semanticObject.eGet(SortingPackage.Literals.TRANSITION__SOURCE, false));
		feeder.accept(grammarAccess.getTransitionAccess().getTargetComponentIDTerminalRuleCall_2_0_1(), semanticObject.eGet(SortingPackage.Literals.TRANSITION__TARGET, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Type returns Type
	 *
	 * Constraint:
	 *     (type='int' | type='String' | type='double' | type='long')
	 */
	protected void sequence_Type(ISerializationContext context, Type semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
