/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.validation;

import org.xtext.example.sorting.validation.AbstractSortingValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SortingValidator extends AbstractSortingValidator {
}
