/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SortingStandaloneSetup extends SortingStandaloneSetupGenerated {

	def static void doSetup() {
		new SortingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
