/*
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.pipesgraph.ui.internal.PipesgraphActivator;

public class PipesGraphUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PipesgraphActivator.getInstance().getInjector("org.xtext.pipesgraph.PipesGraph");
	}

}
