/*
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PipesGraphAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/pipesgraph/parser/antlr/internal/InternalPipesGraph.tokens");
	}
}
