/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.pipesgraph.ui.AbstractPipesGraphUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PipesGraphUiModule extends AbstractPipesGraphUiModule {
  public PipesGraphUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
