/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.sorting;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.sorting.sorting.Filter#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.sorting.sorting.Filter#getInType <em>In Type</em>}</li>
 *   <li>{@link org.xtext.example.sorting.sorting.Filter#getOutType <em>Out Type</em>}</li>
 *   <li>{@link org.xtext.example.sorting.sorting.Filter#getMethod <em>Method</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.sorting.sorting.SortingPackage#getFilter()
 * @model
 * @generated
 */
public interface Filter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.sorting.sorting.SortingPackage#getFilter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.sorting.sorting.Filter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>In Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Type</em>' containment reference.
   * @see #setInType(Type)
   * @see org.xtext.example.sorting.sorting.SortingPackage#getFilter_InType()
   * @model containment="true"
   * @generated
   */
  Type getInType();

  /**
   * Sets the value of the '{@link org.xtext.example.sorting.sorting.Filter#getInType <em>In Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In Type</em>' containment reference.
   * @see #getInType()
   * @generated
   */
  void setInType(Type value);

  /**
   * Returns the value of the '<em><b>Out Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Out Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out Type</em>' containment reference.
   * @see #setOutType(Type)
   * @see org.xtext.example.sorting.sorting.SortingPackage#getFilter_OutType()
   * @model containment="true"
   * @generated
   */
  Type getOutType();

  /**
   * Sets the value of the '{@link org.xtext.example.sorting.sorting.Filter#getOutType <em>Out Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out Type</em>' containment reference.
   * @see #getOutType()
   * @generated
   */
  void setOutType(Type value);

  /**
   * Returns the value of the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' attribute.
   * @see #setMethod(String)
   * @see org.xtext.example.sorting.sorting.SortingPackage#getFilter_Method()
   * @model
   * @generated
   */
  String getMethod();

  /**
   * Sets the value of the '{@link org.xtext.example.sorting.sorting.Filter#getMethod <em>Method</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' attribute.
   * @see #getMethod()
   * @generated
   */
  void setMethod(String value);

} // Filter
