/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.sorting;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sink</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sorting.sorting.SortingPackage#getSink()
 * @model
 * @generated
 */
public interface Sink extends Component
{
} // Sink
