/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting.ide;

import org.xtext.example.sorting.ide.AbstractSortingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SortingIdeModule extends AbstractSortingIdeModule {
}
