/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph.validation;

import org.xtext.pipesgraph.validation.AbstractPipesGraphValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PipesGraphValidator extends AbstractPipesGraphValidator {
}
