/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph.pipesGraph.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.pipesgraph.pipesGraph.PipesGraphPackage;
import org.xtext.pipesgraph.pipesGraph.Sink;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sink</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SinkImpl extends ComponentImpl implements Sink
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SinkImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PipesGraphPackage.Literals.SINK;
  }

} //SinkImpl
