/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph.pipesGraph.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.pipesgraph.pipesGraph.PipesGraphPackage;
import org.xtext.pipesgraph.pipesGraph.Source;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SourceImpl extends ComponentImpl implements Source
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PipesGraphPackage.Literals.SOURCE;
  }

} //SourceImpl
