/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sorting;

import org.xtext.example.sorting.AbstractSortingRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SortingRuntimeModule extends AbstractSortingRuntimeModule {
}
