/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph.ide;

import org.xtext.pipesgraph.ide.AbstractPipesGraphIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PipesGraphIdeModule extends AbstractPipesGraphIdeModule {
}
