/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph;

import org.xtext.pipesgraph.PipesGraphStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PipesGraphStandaloneSetup extends PipesGraphStandaloneSetupGenerated {
  public static void doSetup() {
    new PipesGraphStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
