/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pipesgraph;

import org.xtext.pipesgraph.AbstractPipesGraphRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PipesGraphRuntimeModule extends AbstractPipesGraphRuntimeModule {
}
